image: gitlab/dind
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci
  USER_GITLAB: stalker200368
  APP_NAME: telegrammettingbot
  REPO: telegrammettingbot

stages:
  - build
  - test
  - docker

maven-build:
  image: maven:3-jdk-11
  stage: build
  script: "mvn clean package -B -Dmaven.test.skip=true"
  artifacts:
    paths:
      - target/*.jar

docker-build:
  stage: docker
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t registry.gitlab.com/stalker200368/telegrammettingbot .
    - docker push registry.gitlab.com/yournameingitlab/telegrammettingbot