version: '2'

services:
  app:
    build: .
    container_name: tgbotapp
    depends_on:
      - db
    links:
      - "db:db"
    environment:
      - CONNECTION_STRING=jdbc:postgresql://db:5432/postgres
      - BOT_TOKEN=${BOT_TOKEN}
      - PROXY_HOST=${PROXY_HOST}
      - PROXY_PORT=${PROXY_PORT}
      - PROXY_LOGIN=${PROXY_LOGIN}
      - PROXY_PASSWORD=${PROXY_PASSWORD}
    volumes:
      - ./data:/var/app/data
    restart: always
    ports:
      - "8080:8080"
  db:
    image: 'postgres:13.1-alpine'
    container_name: dbtgbot
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
volumes:
  postgres_volume: {}


